"""Facebook load-more scroll JavaScript payloads。

職責：保留 scroll script 對外匯入入口；posts、comments 與 guard payload
分別由 `scroll_post_scripts.py`、`scroll_comment_scripts.py`、`scroll_guard_scripts.py` 維護。
"""

from __future__ import annotations

from facebook_monitor.facebook.scroll_comment_scripts import (
    CAPTURE_COMMENT_SCROLL_SNAPSHOT_SCRIPT as CAPTURE_COMMENT_SCROLL_SNAPSHOT_SCRIPT,
    COMMENT_SCROLL_HELPERS_SCRIPT as COMMENT_SCROLL_HELPERS_SCRIPT,
    COMMENT_SCROLL_LOAD_MORE_SCRIPT as COMMENT_SCROLL_LOAD_MORE_SCRIPT,
    RESTORE_COMMENT_SCROLL_SNAPSHOT_SCRIPT as RESTORE_COMMENT_SCROLL_SNAPSHOT_SCRIPT,
)
from facebook_monitor.facebook.scroll_guard_scripts import (
    BEGIN_COMMENT_LOAD_MORE_GUARD_SCRIPT as BEGIN_COMMENT_LOAD_MORE_GUARD_SCRIPT,
    END_COMMENT_LOAD_MORE_GUARD_SCRIPT as END_COMMENT_LOAD_MORE_GUARD_SCRIPT,
)
from facebook_monitor.facebook.scroll_post_scripts import (
    CAPTURE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT as CAPTURE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT,
    RESTORE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT as RESTORE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT,
    SCROLL_HELPERS_SCRIPT as SCROLL_HELPERS_SCRIPT,
    SCROLL_LOAD_MORE_SCRIPT as SCROLL_LOAD_MORE_SCRIPT,
    SCROLL_POSITION_SCRIPT as SCROLL_POSITION_SCRIPT,
)

__all__ = [
    "BEGIN_COMMENT_LOAD_MORE_GUARD_SCRIPT",
    "CAPTURE_COMMENT_SCROLL_SNAPSHOT_SCRIPT",
    "CAPTURE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT",
    "COMMENT_SCROLL_HELPERS_SCRIPT",
    "COMMENT_SCROLL_LOAD_MORE_SCRIPT",
    "END_COMMENT_LOAD_MORE_GUARD_SCRIPT",
    "RESTORE_COMMENT_SCROLL_SNAPSHOT_SCRIPT",
    "RESTORE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT",
    "SCROLL_HELPERS_SCRIPT",
    "SCROLL_LOAD_MORE_SCRIPT",
    "SCROLL_POSITION_SCRIPT",
]
