"""Facebook load-more scroll public entrypoint.

職責：保留既有 import path；實際 wrappers 與大型 JavaScript payload 暫放
`scroll_control_runtime.py`，讓 posts / comments extractor 不直接依賴大檔案。
"""

from __future__ import annotations

from facebook_monitor.facebook.scroll_control_runtime import (
    BEGIN_COMMENT_LOAD_MORE_GUARD_SCRIPT as BEGIN_COMMENT_LOAD_MORE_GUARD_SCRIPT,
    CAPTURE_COMMENT_SCROLL_SNAPSHOT_SCRIPT as CAPTURE_COMMENT_SCROLL_SNAPSHOT_SCRIPT,
    CAPTURE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT as CAPTURE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT,
    COMMENT_SCROLL_HELPERS_SCRIPT as COMMENT_SCROLL_HELPERS_SCRIPT,
    COMMENT_SCROLL_LOAD_MORE_SCRIPT as COMMENT_SCROLL_LOAD_MORE_SCRIPT,
    END_COMMENT_LOAD_MORE_GUARD_SCRIPT as END_COMMENT_LOAD_MORE_GUARD_SCRIPT,
    RESTORE_COMMENT_SCROLL_SNAPSHOT_SCRIPT as RESTORE_COMMENT_SCROLL_SNAPSHOT_SCRIPT,
    RESTORE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT as RESTORE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT,
    SCROLL_HELPERS_SCRIPT as SCROLL_HELPERS_SCRIPT,
    SCROLL_LOAD_MORE_SCRIPT as SCROLL_LOAD_MORE_SCRIPT,
    SCROLL_POSITION_SCRIPT as SCROLL_POSITION_SCRIPT,
    begin_comment_load_more_guard as begin_comment_load_more_guard,
    begin_comment_load_more_guard_async as begin_comment_load_more_guard_async,
    capture_comment_scroll_snapshot as capture_comment_scroll_snapshot,
    capture_comment_scroll_snapshot_async as capture_comment_scroll_snapshot_async,
    capture_load_more_scroll_snapshot as capture_load_more_scroll_snapshot,
    capture_load_more_scroll_snapshot_async as capture_load_more_scroll_snapshot_async,
    end_comment_load_more_guard as end_comment_load_more_guard,
    end_comment_load_more_guard_async as end_comment_load_more_guard_async,
    get_scroll_position as get_scroll_position,
    get_scroll_position_async as get_scroll_position_async,
    restore_comment_scroll_snapshot as restore_comment_scroll_snapshot,
    restore_comment_scroll_snapshot_async as restore_comment_scroll_snapshot_async,
    restore_load_more_scroll_snapshot as restore_load_more_scroll_snapshot,
    restore_load_more_scroll_snapshot_async as restore_load_more_scroll_snapshot_async,
    scroll_comment_load_more as scroll_comment_load_more,
    scroll_comment_load_more_async as scroll_comment_load_more_async,
    scroll_load_more as scroll_load_more,
    scroll_load_more_async as scroll_load_more_async,
)

__all__ = [
    "BEGIN_COMMENT_LOAD_MORE_GUARD_SCRIPT",
    "CAPTURE_COMMENT_SCROLL_SNAPSHOT_SCRIPT",
    "CAPTURE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT",
    "COMMENT_SCROLL_HELPERS_SCRIPT",
    "COMMENT_SCROLL_LOAD_MORE_SCRIPT",
    "END_COMMENT_LOAD_MORE_GUARD_SCRIPT",
    "RESTORE_COMMENT_SCROLL_SNAPSHOT_SCRIPT",
    "RESTORE_LOAD_MORE_SCROLL_SNAPSHOT_SCRIPT",
    "SCROLL_HELPERS_SCRIPT",
    "SCROLL_LOAD_MORE_SCRIPT",
    "SCROLL_POSITION_SCRIPT",
    "begin_comment_load_more_guard",
    "begin_comment_load_more_guard_async",
    "capture_comment_scroll_snapshot",
    "capture_comment_scroll_snapshot_async",
    "capture_load_more_scroll_snapshot",
    "capture_load_more_scroll_snapshot_async",
    "end_comment_load_more_guard",
    "end_comment_load_more_guard_async",
    "get_scroll_position",
    "get_scroll_position_async",
    "restore_comment_scroll_snapshot",
    "restore_comment_scroll_snapshot_async",
    "restore_load_more_scroll_snapshot",
    "restore_load_more_scroll_snapshot_async",
    "scroll_comment_load_more",
    "scroll_comment_load_more_async",
    "scroll_load_more",
    "scroll_load_more_async",
]
